project:
  type: book
  output-dir: docs  # <-- Add this line
  resources:
    - images/

book:
  title: "Introduction to Data Science with R"
  author: "Jon McCurdy"
  date: "5/3/2025"
  chapters:
    - index.qmd
    - Lecture-1-What-is-Data.qmd
    - Lecture-2-Data-Detectives.qmd
    - Lecture-3-R-Basics.qmd
    - Lecture-4-R-and-Vectors.qmd
    - Lecture-5-More-R.qmd
    - Lecture-6-Reproducibility-with-RMarkdown.qmd
    - Lecture-7-Dataframes-in-R.qmd
    - Lecture-8-Exploratory-Data-Analysis.qmd
    - Lecture-9-More-EDA-and-Loading-in-Data.qmd
    - Lecture-10-Probability-Distributions.qmd
    - Lecture-11-Describing-a-Distribution.qmd
    - Lecture-12-Central-Limit-Theorem.qmd
    - Lecture-13-Confidence-Intervals.qmd
    - Lecture-14-Hypothesis-Testing.qmd
    - Lecture-15-Visualizations.qmd
    #- summary.qmd
    #- references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: 
      - callout_custom.css
      - style.css
      - webex.css
    include-in-header: webex.js
  pdf:
    documentclass: scrreprt

editor: visual

