{
  "hash": "c3a5189beb9a85c1911a34956a9af9ce",
  "result": {
    "engine": "knitr",
    "markdown": "# Loading Data in R & EDA\n\n::: learning-goals\n-   Load external data into R using read.csv() or the RStudio Import Dataset interface.\n-   Examine the structure of a dataset using str() and determine which variables should be converted to factors.\n-   Use the table() function to summarize and visualize categorical variables and their combinations with barplots.\n-   Use logical vectors to filter data and compute summaries like means for specific subgroups.\n-   Use the aggregate() function to compute summary statistics for quantitative variables grouped by one or more categorical variables.\n:::\n\n::: callout-tip\n## Supplemental Material\n\n<a href=\"Reading-Guide/L9-Reading-Guide.pdf\" download> 📄 Download the lecture's Reading Guide </a>\n\n<a href=\"Assignments/Data_200_df.csv\" download> 📎 Download the Data used throughout the lecture </a> <br>\n<a href=\"Assignments/Campus_Habits_19.csv\" download> 📎 Download the Data used for the lab </a>\n:::\n\n\n## Loading Data into R\n\nSometimes we are interested in using data that isn't in R. If this is the case, we will have to load the data into R ourselves using a CSV file. To follow along with this lecture writeup, you can download the dataset called \"Data_200_df.csv\" from the Supplemental Material found above. Now to load data into R there are several different ways we can do it. One way is using the *read.csv()* function where we pass the file path into the function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# My file is saved on my Desktop, yours might be saved under Downloads\nData_200_df <- read.csv(\"Desktop/Data_200_df.csv\")\n```\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nAn easier method to load data into R (so we don't have to memorize the function!) is to go to \"File -$>$ Import Dataset -$>$ From Text (base)\" and then select the file we want to import. Using this method also makes it easier for us to customize our request like identifying if we have row/column headers or if all of the strings should be factors.\n\n\\begin{watch}{}{}\n    \\href{https://youtu.be/603gU61EWQ4}{Loading Data into R}\n\\end{watch}\n\n## Converting Vectors to Factors\n\nNow that we have the data loaded into our R environment, we can start to do some Exploratory Data Analysis (EDA) on it. The first thing we will want to do is look at the structure of the dataset to see what we are dealing with. This can be done using the *str()* function. In our case here, we do not have any documentation to compare our data or to learn about the dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(Data_200_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t50 obs. of  6 variables:\n $ names : chr  \"Theresa\" \"Clyde\" \"Katrina\" \"Ricky\" ...\n $ ages  : int  21 20 19 19 19 23 18 21 24 23 ...\n $ state : chr  \"NY\" \"NC\" \"NY\" \"NY\" ...\n $ year  : chr  \"Freshman\" \"Freshman\" \"Sophmore\" \"Sophmore\" ...\n $ majors: chr  \"Psych\" \"Comp-Sci\" \"Math\" \"Psych\" ...\n $ sport : int  0 1 1 0 1 1 0 0 0 0 ...\n```\n\n\n:::\n:::\n\n\nLooking at this, it would probably make sense to turn a couple of these columns into factors because these variables represent categories rather than measurements. This can be done using the *factor()* function and then altering the levels if need be (since sport is given as 0 or 1 we may want to alter the level name to No and Yes). We should only convert a vector to a factor column if there are finite number of categories and there are multiple occurrences of each category. So, we will not need to convert the \"names\" column since they are all unique and there are virtually infinite number of possibilities.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nData_200_df$state_f <- factor(Data_200_df$state)\nData_200_df$year_f <- factor(Data_200_df$year)\nData_200_df$majors_f <- factor(Data_200_df$majors)\n\nData_200_df$sport_f <- as.factor(Data_200_df$sport)\nlevels(Data_200_df$sport_f) <- c(\"No\", \"Yes\")\n```\n:::\n\n\nConverting variables to factors is especially important because many of the tools we use for exploratory data analysis, such as *table()* and *aggregate()*, are designed to work with categorical variables. If our categories are stored as characters or numbers without meaning, our summaries can be misleading or harder to interpret.\n\n::: {.callout-tip title=\"Try it Out\"}\nEmmit is working with the `iris` dataset and wants to treat Species as a factor and create a new categorical variable called `SepalLength_group` by cutting Sepal.Length into three groups (Short, Medium, Long). Help show Emmit how he accomplish this task in R.\n\n<details>\n\n<summary>Click to see the solution</summary>\n\n{{< video https://www.youtube.com/embed/-Y2TVJR7y7w?modestbranding=1&rel=0 >}}\n\n</details>\n:::\n\n\\begin{watch}{}{}\n    \\href{https://youtu.be/4oSEQDN8C1c}{Converting Vectors into Factors}\n\\end{watch}\n\n## Utilizing the Table function\n\nTo better understand the dataset, it is helpful to calculate some descriptive statistics and create some visualizations as well. To calculate descriptive statistics for a categorical variable we can use the *table()* function. This will tell us how many times each category occurs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(Data_200_df$year_f)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFreshman   Junior   Senior Sophmore \n      15       12       10       13 \n```\n\n\n:::\n\n```{.r .cell-code}\nbarplot(table(Data_200_df$year_f))\n```\n\n::: {.cell-output-display}\n![](Lecture-9-More-EDA-and-Loading-in-Data_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(Data_200_df$majors_f)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    Chem Comp-Sci     Data  History     Math    Psych \n      12        9       10        2       10        7 \n```\n\n\n:::\n\n```{.r .cell-code}\nbarplot(table(Data_200_df$majors_f))\n```\n\n::: {.cell-output-display}\n![](Lecture-9-More-EDA-and-Loading-in-Data_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nSo, this shows us the number of students who are Juniors, and the number of students who are Data majors, but can we determine how many Junior Data majors we have? One way we could do this is by using a logical vector, which is a TRUE/FALSE statement applied to every row of the dataset. This expression evaluates to TRUE only for rows where both conditions are satisfied, and sum() counts how many TRUE values we have.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(Data_200_df$year_f==\"Junior\" & Data_200_df$majors_f==\"Data\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n:::\n\n\nIf we are interested in other combinations we certainly could carry out the process again and again for all 24 combinations. Another way that will count the number of students who fall into each category is to use the *table()* function but pass two categorical variables into it. It will count the number of occurrences for each combination of groupings.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(Data_200_df$majors_f, Data_200_df$year_f)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          \n           Freshman Junior Senior Sophmore\n  Chem            4      3      2        3\n  Comp-Sci        4      3      1        1\n  Data            1      2      2        5\n  History         1      1      0        0\n  Math            3      1      4        2\n  Psych           2      2      1        2\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip title=\"Try it Out\"}\nEmmit is now interested in determing how many flowers fall into each `Species` category, each `SepalLength_group` category, and how many fall into the combination of the two groups. Help show Emmit how this can be done in R along with visualizing the data.\n\n<details>\n\n<summary>Click to see the solution</summary>\n\n{{< video https://www.youtube.com/embed/-Y2TVJR7y7w?modestbranding=1&rel=0 >}}\n\n</details>\n:::\n\n\\begin{watch}{}{}\n    \\href{https://youtu.be/Oq4GZnTAHNk}{Using the \\textit{table()} Function with multiple variables}\n\\end{watch}\n\n## Utilizing the Aggregate function\n\nAnother type of descriptive statistic that we can calculate is the mean on one of the variables (age in our case). While this is helpful, it might also be interesting to see the mean age by major, and to do this we can use a logical vector within our index-selection brackets.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(Data_200_df$ages)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 20.7\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(Data_200_df$ages[Data_200_df$majors_f==\"Psych\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 20.42857\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(Data_200_df$ages[Data_200_df$majors_f==\"Chem\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 20.91667\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(Data_200_df$ages[Data_200_df$majors_f==\"History\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 18\n```\n\n\n:::\n:::\n\n\nRunning a line of code for every major is tedious and cumbersome. To do it more efficiently we could use the *aggregate()* function. In this function, we will pass in the variable we want to calculate, then specify what we want to group *by* (which needs to be in the *list()* function and be a categorical variable), and finally specifying the function we want to run. The general setup for this function will be:\n\n```         \naggregate(Quantitative_Variable, by = list(Categorical_Grouping_Variable), math_function)\n```\n\nAn example of this function can be seen below. The output is a new data frame where each row corresponds to one group and the final column contains the computed summary statistic.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naggregate(Data_200_df$ages, by=list(Data_200_df$majors_f), mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Group.1        x\n1     Chem 20.91667\n2 Comp-Sci 21.44444\n3     Data 19.90000\n4  History 18.00000\n5     Math 21.30000\n6    Psych 20.42857\n```\n\n\n:::\n:::\n\n\n\\begin{watch}{}{}\n    \\href{https://youtu.be/k5Wgr1VVUhw}{Using the \\textit{aggregate()} Function}\n\\end{watch}\n\nThe way we can read the output from above is that the average age of Chemistry majors is 20.92, the average age of Computer Science majors is 21.44, and so on. We can divide our population up into more groups if we want. For instance, maybe we want to find the average age of people based on their major and whether they play a sport. To do this we will pass in two variables in the *by* argument.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naggregate(Data_200_df$ages, \n          by=list(majors = Data_200_df$majors_f, \n                  sports = Data_200_df$sport_f), \n          mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     majors sports        x\n1      Chem     No 20.60000\n2  Comp-Sci     No 21.80000\n3      Data     No 20.60000\n4      Math     No 21.20000\n5     Psych     No 21.00000\n6      Chem    Yes 21.14286\n7  Comp-Sci    Yes 21.00000\n8      Data    Yes 19.20000\n9   History    Yes 18.00000\n10     Math    Yes 21.40000\n11    Psych    Yes 19.00000\n```\n\n\n:::\n:::\n\n\nFor this output, we would interpret it similarly. We would say the average age of Chemistry majors who do not play a sport is 20.60, and the average age of Chemistry majors who play a sport is 21.14. We can then do it for all possible combinations of majors and whether they play a sport or not. We can also carry this out using different functions like sd, length, median, and so on.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naggregate(Data_200_df$ages, by=list(state= Data_200_df$state_f), sd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  state        x\n1    MD 2.345208\n2    NC 1.378405\n3    NY 2.101805\n4    PA 2.645751\n5    VA 1.612452\n6    WV 2.438123\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip title=\"Try it Out\"}\nEmmit believes that there is a difference in the `Petal.Length` for different `Species` types. Help show Emmit how this can be determined in R using the `aggregate()` function.\n\n<details>\n\n<summary>Click to see the solution</summary>\n\n{{< video https://www.youtube.com/embed/-Y2TVJR7y7w?modestbranding=1&rel=0 >}}\n\n</details>\n:::\n\n\\begin{watch}{}{}\n    \\href{https://youtu.be/OsadIjZEIR0}{Using the \\textit{aggregate()} Function with Multiple Groupings}\n\\end{watch}\n\nWithin this section, we have learned two powerful functions which help us summarize categorical and quantitative data. We should think about what data we have present though before we run the code. If we try to run the table function on data that is not categorical (with relatively few categories) or if we try to use the aggregate function and group by quantitative data then the output will not be readable due to the number of possibilities. Therefore, it is important to think about what type of data we are passing into each function and whether the output is particularly useful.\n\n::: {.chapter-resources}\n\n<div class=\"chapter-resources-header\">\n  <a href=\"https://youtu.be/U7wcOB7548Q\" target=\"_blank\">Lecture Video</a>\n</div>\n\n<div class=\"chapter-resources-grid\">\n  <div><a href=\"Assignments/Data-200-L9-Inclass-Assignment.pdf\" target=\"_blank\">In-Class Exercises</a></div>\n  <div><a href=\"https://youtu.be/rrhstyGNcow\" target=\"_blank\">In-Class Exercises Video Solutions</a></div>\n</div>\n\n<div class=\"chapter-resources-footer lab-row\">\n  <a href=\"Assignments/Data-200-L9-Lab.pdf\" target=\"_blank\">Lab Problems</a>\n</div>\n\n<div class=\"chapter-resources-footer problem-set-row\">\n  <a href=\"Assignments/Data-200-L9-Problem-Set.pdf\" target=\"_blank\">Problem Set Questions</a>\n</div>\n\n:::\n",
    "supporting": [
      "Lecture-9-More-EDA-and-Loading-in-Data_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}